spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: vishnu123
  jpa:
    show-sql: true
  jwt:
    secret : ${JWT_SECRET}
    accessTokenExpiration : 900 #15m
    refreshTokenExpiration : 604800 #7d
